### ISSUE TITLE
E2E Tests are failing with DB- Connection timeout. 

### ISSUE THREAD

**Issue by hrishidkakkad** [andrechristikan/ack-nestjs-boilerplate-mongoose#111]
E2E Tests are failing with DB- Connection timeout. Shouldn't this be mocked?

**Comment by andrechristikan** [comment]
Before we run e2e test, we must to run mongodb instance and pass the integration test

To run integration test, 
```bash
yarn test:integration
```

For more information you can read the documentation
https://andrechristikan.github.io/ack-nestjs-boilerplate-docs/#/getting-started/readme

**Comment by hrishikeshdkakkad** [comment]
But shouldn't it be run on MongoDB memory Server? @andrechristikan 
[MongoDB Memory Server](https://github.com/nodkz/mongodb-memory-server)

This would avoid spinning up a MongoDB instance. Because, how would we do that in a CI pipeline environment?

**Comment by andrechristikan** [comment]
Actually, i never heard about MongoDB memory Server. 
Maybe that will be useful as options for running mongodb instance. 
Thanks for mention @hrishidkakkad 

By the way in CI Environment, i always use service (or container) to help me while running the test
That why in [test github workflow](https://github.com/andrechristikan/ack-nestjs-boilerplate-mongoose/blob/main/.github/workflows/test.yml), there have service named `mongodb`

```yml
services:
 mongodb:
  image: mongo:latest
  options: >-
    --health-cmd mongo
    --health-interval 10s
    --health-timeout 5s
    --health-retries 5
  ports:
    - 27017:27017
```

**Comment by andrechristikan** [comment]
Actually, i never heard about MongoDB memory Server. 
Maybe that will be useful as options for running mongodb instance. 
Thanks for mention @hrishikeshdkakkad 

By the way in CI Environment, i always use service (or container) to help me while running the test
That why in [test github workflow](https://github.com/andrechristikan/ack-nestjs-boilerplate-mongoose/blob/main/.github/workflows/test.yml), there have service named `mongodb`

```yml
services:
 mongodb:
  image: mongo:latest
  options: >-
    --health-cmd mongo
    --health-interval 10s
    --health-timeout 5s
    --health-retries 5
  ports:
    - 27017:27017
```
